version: '3'
services:
  podcast-server:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ~/podcast_music_files/:/volumes/music_files/
    environment:
      - APP_ROOT_URL=http://localhost:8080/
